# --------------------------------------------------------------------------- #
# 0001_initial.py                                                             #
# --------------------------------------------------------------------------- #
# flake8: noqa  (auto-generated by Django, style adjustments only)           #
"""
Initial database schema for the *chat* application.

This migration creates the ``Conversation`` and ``ChatMessage`` tables used by
the findus project.  It is auto-generated by Django's ``makemigrations`` and
should not be edited manually aside from adding explanatory docstrings.
"""
# Generated by Django 5.2.4 on 2025-08-03 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create core chat models (`Conversation`, `ChatMessage`)."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        default='New Conversation',
                        help_text='Conversation title (can be renamed later).',
                        max_length=255,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('message', models.TextField(help_text='Raw user prompt')),
                ('response', models.TextField(help_text='Gemini response')),
                (
                    'grammar_analysis',
                    models.TextField(
                        blank=True,
                        help_text='Grammar and spelling analysis from Gemini',
                        null=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'conversation',
                    models.ForeignKey(
                        help_text='Conversation this message belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='chat.conversation',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['conversation_id', 'created_at'],
            },
        ),
    ]
