# Generated by Django 5.2.4 on 2025-08-04 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterActionReport',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'analysis_content',
                    models.TextField(
                        help_text='AI-generated analysis of language patterns and recommendations'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'conversation',
                    models.ForeignKey(
                        help_text='Conversation this report analyzes',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reports',
                        to='chat.conversation',
                    ),
                ),
            ],
            options={
                'verbose_name': 'After-Action Report',
                'verbose_name_plural': 'After-Action Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
