# Generated by Django 5.2.6 on 2025-09-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='language',
            field=models.CharField(
                choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German')],
                default='en',
                help_text='Language for this conversation',
                max_length=2,
            ),
        ),
    ]
