# Generated by Django 5.2.6 on 2025-09-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='analysis_language',
            field=models.CharField(
                choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German')],
                default='en',
                help_text='Language for grammar analysis feedback',
                max_length=2,
            ),
        ),
    ]
