# Generated by Django 5.2.6 on 2025-09-24 17:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_grammarconcept_errorpattern_conceptmastery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='study_streak_days',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_messages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_minutes',
            field=models.IntegerField(
                default=15, help_text='Daily practice goal in minutes'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(
                default='UTC', help_text="User's timezone for scheduling", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='native_language',
            field=models.CharField(
                choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German')],
                default='en',
                help_text="User's native language",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(
                default=dict, help_text='User preferences and settings'
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                help_text='Associated user account',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='LanguageProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'target_language',
                    models.CharField(
                        choices=[
                            ('en', 'English'),
                            ('es', 'Spanish'),
                            ('de', 'German'),
                        ],
                        help_text='Language being learned',
                        max_length=2,
                    ),
                ),
                (
                    'current_level',
                    models.CharField(
                        choices=[
                            ('A1', 'A1 - Beginner'),
                            ('A2', 'A2 - Elementary'),
                            ('B1', 'B1 - Intermediate'),
                            ('B2', 'B2 - Upper-Intermediate'),
                            ('C1', 'C1 - Advanced'),
                            ('C2', 'C2 - Proficient'),
                        ],
                        default='A1',
                        help_text='Current estimated CEFR level',
                        max_length=2,
                    ),
                ),
                (
                    'total_messages',
                    models.IntegerField(
                        default=0, help_text='Total messages sent in this language'
                    ),
                ),
                (
                    'total_practice_time',
                    models.IntegerField(
                        default=0, help_text='Total practice time in minutes'
                    ),
                ),
                (
                    'study_streak_days',
                    models.IntegerField(
                        default=0, help_text='Current consecutive days of practice'
                    ),
                ),
                (
                    'longest_streak',
                    models.IntegerField(
                        default=0, help_text='Longest study streak achieved'
                    ),
                ),
                (
                    'last_activity',
                    models.DateTimeField(
                        blank=True,
                        help_text='Last time user practiced this language',
                        null=True,
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Whether user is actively learning this language',
                    ),
                ),
                (
                    'proficiency_score',
                    models.FloatField(
                        default=0.0,
                        help_text='Overall proficiency score (0.0-1.0)',
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    'confidence_level',
                    models.FloatField(
                        default=0.0,
                        help_text='Confidence in proficiency assessment',
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    'vocabulary_size',
                    models.IntegerField(
                        default=0, help_text='Estimated vocabulary size'
                    ),
                ),
                (
                    'grammar_accuracy',
                    models.FloatField(
                        default=0.0,
                        help_text='Grammar accuracy score',
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    'fluency_score',
                    models.FloatField(
                        default=0.0,
                        help_text='Fluency assessment score',
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    'weak_areas',
                    models.JSONField(
                        default=list,
                        help_text='List of grammar areas needing improvement',
                    ),
                ),
                (
                    'strong_areas',
                    models.JSONField(
                        default=list, help_text='List of grammar areas showing strength'
                    ),
                ),
                (
                    'learning_goals',
                    models.JSONField(
                        default=list,
                        help_text="User's learning goals for this language",
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User learning this language',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='language_profiles',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Language Profile',
                'verbose_name_plural': 'Language Profiles',
                'indexes': [
                    models.Index(
                        fields=['user', 'target_language'],
                        name='chat_langua_user_id_5ab2bb_idx',
                    ),
                    models.Index(
                        fields=['current_level'], name='chat_langua_current_6c7482_idx'
                    ),
                    models.Index(
                        fields=['last_activity'], name='chat_langua_last_ac_3119f9_idx'
                    ),
                    models.Index(
                        fields=['is_active'], name='chat_langua_is_acti_225beb_idx'
                    ),
                ],
                'unique_together': {('user', 'target_language')},
            },
        ),
    ]
