# Generated by Django 5.2.6 on 2025-09-24 17:51

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_refactor_userprofile_to_languageprofile'),
    ]

    operations = [
        CreateExtension('vector'),
    ]
