# Generated by Django 5.2.6 on 2025-09-24 17:55

import chat.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20250924_1751'),
    ]

    operations = [
        # Remove the old JSONField
        migrations.RemoveField(
            model_name='grammarconcept',
            name='embedding',
        ),
        # Add the new VectorField
        migrations.AddField(
            model_name='grammarconcept',
            name='embedding',
            field=chat.fields.VectorField(
                blank=True,
                dimensions=768,
                help_text='Vector embedding for similarity searches',
                null=True,
            ),
        ),
    ]
