# Generated by Django 5.2.6 on 2025-09-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_recreate_embedding_as_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageprofile',
            name='longest_streak',
        ),
        migrations.RemoveField(
            model_name='languageprofile',
            name='study_streak_days',
        ),
    ]
