# Generated by Django 5.2.6 on 2025-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_streak_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorpattern',
            name='error_type',
            field=models.CharField(help_text='Category of error', max_length=100),
        ),
        migrations.AlterField(
            model_name='grammarconcept',
            name='name',
            field=models.CharField(
                help_text='Human-readable name of the grammar concept', max_length=500
            ),
        ),
    ]
