"""Django database migrations for the chat application.

This package contains database migrations that track schema changes for the
chat models. These files are auto-generated by Django and should not be
modified manually unless you know what you're doing.

To generate a new migration:
    python manage.py makemigrations

To apply migrations:
    python manage.py migrate
"""
