FROM mcr.microsoft.com/devcontainers/python:3.13

SHELL ["/bin/bash", "-c"]

# (Optional) Install any additional OS packages you want here
# RUN apt-get update && apt-get install -y <your-package-list>

# (Optional) Install pip requirements if not handled by postCreateCommand
# COPY requirements.txt .
# RUN pip install -r requirements.txt
