"""
Django settings for findus project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import List

import logfire
from dotenv import load_dotenv

# Load environment variables from a `.env` file located in the project root.
# This must be done **before** we reference any env vars (e.g. GEMINI_API_KEY).
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)-d&ggax6&9*2(^4u7-00ltgk-o%g5=*rq_oip&@zsp1281!$='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Explicit type annotation so static type-checkers (mypy, Pyright, etc.) know
# the expected value type.
ALLOWED_HOSTS: List[str] = ['testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django_extensions',
    # Local apps
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'findus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'findus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------------- #
# Google Gemini API                                                           #
# --------------------------------------------------------------------------- #

# Fetch the API key from the environment.  Expect developers to create a
# local ``.env`` file (ignored via .gitignore) with::
#     GEMINI_API_KEY=your_api_key_here
#
# This avoids accidentally leaking credentials in source control.

GEMINI_API_KEY: str | None = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise RuntimeError(
        "GEMINI_API_KEY not set.\n"
        "Create a `.env` file in the project root with a line like:\n"
        "GEMINI_API_KEY=your_api_key_here"
    )

# --------------------------------------------------------------------------- #
# Logfire configuration                                                       #
# --------------------------------------------------------------------------- #

LOGFIRE_TOKEN: str | None = os.getenv("LOGFIRE_KEY")

if not LOGFIRE_TOKEN:
    raise RuntimeError(
        "LOGFIRE_KEY not set.\n"
        "Create a `.env` file in the project root with a line like:\n"
        "LOGFIRE_KEY=your_logfire_key_here"
    )

logfire.configure(
    token=LOGFIRE_TOKEN,
    service_name="findus-django",
    service_version="1.0.0",
    environment="development",
)

logfire.instrument_django()
logfire.instrument_sqlite3()

# --------------------------------------------------------------------------- #
# Django-Extensions configuration                                             #
# --------------------------------------------------------------------------- #

# Use IPython for the excellent auto-import and rich-traceback experience
# provided by django-extensions’ *shell_plus* command.
SHELL_PLUS = "ipython"

# ---------------------------------------------------------------------------
# Authentication redirects
# ---------------------------------------------------------------------------
# Where Django should redirect unauthenticated users who attempt to access
# `@login_required` views.
LOGIN_URL = 'login'
# Where to send users right after a successful login (when no `next` parameter
# is present in the URL).  We point to the chat landing page.
LOGIN_REDIRECT_URL = 'home'
# After logging out, users are returned to the login page.
LOGOUT_REDIRECT_URL = 'login'
