"""
Django settings for findus project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import List

import dj_database_url
import logfire
from dotenv import load_dotenv

# Load environment variables from a `.env` file located in the project root.
# This must be done **before** we reference any env vars (e.g. GEMINI_API_KEY).
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Explicit type annotation so static type-checkers (mypy, Pyright, etc.) know
# the expected value type.
ALLOWED_HOSTS: List[str] = os.getenv(
    'ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0'
).split(',')
if os.getenv('HEROKU_APP_NAME'):
    ALLOWED_HOSTS.append(f"{os.getenv('HEROKU_APP_NAME')}.herokuapp.com")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django_extensions',
    # Local apps
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'findus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'findus.wsgi.application'
ASGI_APPLICATION = 'findus.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL on Heroku, SQLite locally
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'CONN_MAX_AGE': 0,  # Disable persistent connections for async
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------------- #
# Google Gemini API                                                           #
# --------------------------------------------------------------------------- #

# Fetch the API key from the environment.  Expect developers to create a
# local ``.env`` file (ignored via .gitignore) with::
#     GEMINI_API_KEY=your_api_key_here
#
# This avoids accidentally leaking credentials in source control.

GEMINI_API_KEY: str | None = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY and not os.getenv(
    'DATABASE_URL'
):  # Allow missing key in production if not needed
    raise RuntimeError(
        "GEMINI_API_KEY not set.\n"
        "Create a `.env` file in the project root with a line like:\n"
        "GEMINI_API_KEY=your_api_key_here"
    )

# --------------------------------------------------------------------------- #
# Logfire configuration                                                       #
# --------------------------------------------------------------------------- #

LOGFIRE_TOKEN: str | None = os.getenv("LOGFIRE_KEY")

if LOGFIRE_TOKEN:
    logfire.configure(
        token=LOGFIRE_TOKEN,
        service_name="findus-django",
        service_version="1.0.0",
        environment="production" if os.getenv('DATABASE_URL') else "development",
    )

    logfire.instrument_django()
    if not os.getenv('DATABASE_URL'):  # Only instrument SQLite in development
        logfire.instrument_sqlite3()
    logfire.instrument_pydantic_ai()
elif not os.getenv('DATABASE_URL'):  # Only require in development
    raise RuntimeError(
        "LOGFIRE_KEY not set.\n"
        "Create a `.env` file in the project root with a line like:\n"
        "LOGFIRE_KEY=your_logfire_key_here"
    )

# --------------------------------------------------------------------------- #
# Django-Extensions configuration                                             #
# --------------------------------------------------------------------------- #

# Use IPython for the excellent auto-import and rich-traceback experience
# provided by django-extensions’ *shell_plus* command.
SHELL_PLUS = "ipython"

# ---------------------------------------------------------------------------
# Authentication redirects
# ---------------------------------------------------------------------------
# Where Django should redirect unauthenticated users who attempt to access
# `@login_required` views.
LOGIN_URL = 'login'
# Where to send users right after a successful login (when no `next` parameter
# is present in the URL).  We point to the chat landing page.
LOGIN_REDIRECT_URL = 'home'
# After logging out, users are returned to the login page.
LOGOUT_REDIRECT_URL = 'login'
